<?binding.jca BusinesServiceStatus_db.jca?>
<wsdl:definitions name="BusinesServiceStatus" targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/AlphaSOAPaaS/PaasProvisioning/BusinesServiceStatus" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/AlphaSOAPaaS/PaasProvisioning/BusinesServiceStatus" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:top="http://xmlns.oracle.com/pcbpel/adapter/db/top/BusinesServiceStatus">
    <plt:partnerLinkType name="BusinesServiceStatus_plt">
        <plt:role name="BusinesServiceStatus_role">
            <plt:portType name="tns:BusinesServiceStatus_ptt"/>
        </plt:role>
    </plt:partnerLinkType>
    <wsdl:types>
        <schema xmlns="http://www.w3.org/2001/XMLSchema">
            <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/BusinesServiceStatus" schemaLocation="xsd/BusinesServiceStatus_table.xsd"/>
        </schema>
    </wsdl:types>
    <wsdl:message name="SBusinessServiceCollection_msg">
        <wsdl:part name="SBusinessServiceCollection" element="top:SBusinessServiceCollection"/>
    </wsdl:message>
    <wsdl:portType name="BusinesServiceStatus_ptt">
        <wsdl:operation name="update">
            <wsdl:input message="tns:SBusinessServiceCollection_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
