<?binding.jca DequeueBusinesService_db.jca?>
<wsdl:definitions name="DequeueBusinesService" targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/AlphaSOAPaaS/PaasProvisioning/DequeueBusinesService" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/AlphaSOAPaaS/PaasProvisioning/DequeueBusinesService" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:top="http://xmlns.oracle.com/pcbpel/adapter/db/top/DequeueBusinesService">
    <plt:partnerLinkType name="DequeueBusinesService_plt">
        <plt:role name="DequeueBusinesService_role">
            <plt:portType name="tns:DequeueBusinesService_ptt"/>
        </plt:role>
    </plt:partnerLinkType>
    <wsdl:types>
        <schema xmlns="http://www.w3.org/2001/XMLSchema">
            <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/DequeueBusinesService" schemaLocation="xsd/DequeueBusinesService_table.xsd"/>
        </schema>
    </wsdl:types>
    <wsdl:message name="SQueueCollection_msg">
        <wsdl:part name="SQueueCollection" element="top:SQueueCollection"/>
    </wsdl:message>
    <wsdl:portType name="DequeueBusinesService_ptt">
        <wsdl:operation name="receive">
            <wsdl:input message="tns:SQueueCollection_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
