<?binding.jca GetBusinessService_db.jca?>
<wsdl:definitions name="GetBusinessService" targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/AlphaSOAPaaS/PaasProvisioning/GetBusinessService" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/AlphaSOAPaaS/PaasProvisioning/GetBusinessService" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:top="http://xmlns.oracle.com/pcbpel/adapter/db/top/GetBusinessService">
    <plt:partnerLinkType name="GetBusinessService_plt">
        <plt:role name="GetBusinessService_role">
            <plt:portType name="tns:GetBusinessService_ptt"/>
        </plt:role>
    </plt:partnerLinkType>
    <wsdl:types>
        <schema xmlns="http://www.w3.org/2001/XMLSchema">
            <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/GetBusinessService" schemaLocation="xsd/GetBusinessService_table.xsd"/>
        </schema>
    </wsdl:types>
    <wsdl:message name="GetBusinessServiceSelect_inputParameters">
        <wsdl:part name="GetBusinessServiceSelect_inputParameters" element="top:GetBusinessServiceSelect_sQueueIdInputParameters"/>
    </wsdl:message>
    <wsdl:message name="PBusinessServiceCollection_msg">
        <wsdl:part name="PBusinessServiceCollection" element="top:PBusinessServiceCollection"/>
    </wsdl:message>
    <wsdl:portType name="GetBusinessService_ptt">
        <wsdl:operation name="GetBusinessServiceSelect">
            <wsdl:input message="tns:GetBusinessServiceSelect_inputParameters"/>
            <wsdl:output message="tns:PBusinessServiceCollection_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
