<?xml version="1.0" encoding="UTF-8" ?>
<?oracle-xsl-mapper
  <!-- SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY. -->
  <mapSources>
    <source type="WSDL">
      <schema location="../GetBusinessService.wsdl"/>
      <rootElement name="PBusinessServiceCollection" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/GetBusinessService"/>
    </source>
  </mapSources>
  <mapTargets>
    <target type="WSDL">
      <schema location="http://localhost.localdomain:7001/soa-infra/services/default/PaaSProvisioningApproval/PaasApprovalProcess.wsdl"/>
      <rootElement name="start" namespace="http://xmlns.oracle.com/bpmn/bpmnProcess/PaasApprovalProcess"/>
    </target>
  </mapTargets>
  <!-- GENERATED BY ORACLE XSL MAPPER 11.1.1.7.0(build 130301.0647.0008) AT [FRI JAN 17 15:47:41 EST 2014]. -->
?>
<xsl:stylesheet version="1.0"
                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:bpws="http://schemas.xmlsoap.org/ws/2003/03/business-process/"
                xmlns:bpel="http://docs.oasis-open.org/wsbpel/2.0/process/executable"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns:bpm="http://xmlns.oracle.com/bpmn20/extensions"
                xmlns:SOAP-ENC="http://schemas.xmlsoap.org/soap/encoding/"
                xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
                xmlns:wsdlsoap="http://schemas.xmlsoap.org/wsdl/soap/"
                xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                xmlns:ora="http://schemas.oracle.com/xpath/extension"
                xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator"
                xmlns:ns0="http://xmlns.oracle.com/bpmn/bpmnProcess/PaasApprovalProcess"
                xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction"
                xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue"
                xmlns:hwf="http://xmlns.oracle.com/bpel/workflow/xpath"
                xmlns:med="http://schemas.oracle.com/mediator/xpath"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:ids="http://xmlns.oracle.com/bpel/services/IdentityService/xpath"
                xmlns:xdk="http://schemas.oracle.com/bpel/extension/xpath/function/xdk"
                xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                xmlns:top="http://xmlns.oracle.com/pcbpel/adapter/db/top/GetBusinessService"
                xmlns:bpmn="http://schemas.oracle.com/bpm/xpath"
                xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/AlphaSOAPaaS/PaasProvisioning/GetBusinessService"
                xmlns:tns6="http://www.alphaoffice.com/ns/BusinesService"
                xmlns:ldap="http://schemas.oracle.com/xpath/extension/ldap"
                exclude-result-prefixes="xsi xsl plt wsdl xsd top tns SOAP-ENC wsdlsoap ns0 tns6 xp20 bpws bpel bpm ora socket mhdr oraext dvm hwf med ids xdk xref bpmn ldap">
  <xsl:template match="/">
    <ns0:start>
      <tns6:BusinessService>
        <xsl:for-each select="/top:PBusinessServiceCollection/top:PBusinessService/top:pTechnicalServiceCollection/top:PTechnicalService">
          <tns6:TechnicalService>
            <tns6:TechnicalServiceId>
              <xsl:value-of select="top:id"/>
            </tns6:TechnicalServiceId>
            <tns6:ServiceName>
              <xsl:value-of select="top:name"/>
            </tns6:ServiceName>
            <tns6:Cost>
              <xsl:value-of select="top:cost"/>
            </tns6:Cost>
          </tns6:TechnicalService>
        </xsl:for-each>
        <tns6:BusinessServiceId>
          <xsl:value-of select="/top:PBusinessServiceCollection/top:PBusinessService/top:sBusinessServiceId"/>
        </tns6:BusinessServiceId>
        <tns6:ServiceName>
          <xsl:value-of select="/top:PBusinessServiceCollection/top:PBusinessService/top:name"/>
        </tns6:ServiceName>
        <tns6:FirstName>
          <xsl:value-of select="/top:PBusinessServiceCollection/top:PBusinessService/top:firstName"/>
        </tns6:FirstName>
        <tns6:LastName>
          <xsl:value-of select="/top:PBusinessServiceCollection/top:PBusinessService/top:lastName"/>
        </tns6:LastName>
        <tns6:Email>
          <xsl:value-of select="/top:PBusinessServiceCollection/top:PBusinessService/top:userEmail"/>
        </tns6:Email>
        <tns6:TotalCost>
          <xsl:value-of select="/top:PBusinessServiceCollection/top:PBusinessService/top:totalCost"/>
        </tns6:TotalCost>
      </tns6:BusinessService>
    </ns0:start>
  </xsl:template>
</xsl:stylesheet>
